#pragma once

#include "Core.hpp"
#include "Mesh.hpp"

void LoadCourseModels(ES::Engine::Core &core, const glm::vec3 &position, const glm::quat &rotation, const glm::vec3 &size);

void LoadCourseCollision(ES::Engine::Core &core, const glm::vec3 &size);

void LoadCourseTextures(ES::Engine::Core &core);

void UnloadCourseTextures(ES::Engine::Core &core);

static const std::vector<std::tuple<std::string, std::string, bool>> textureList = {
    {"tex_PLACEHOLDER", "asset/textures/placeholder.png", true},
    {"tex_CEMSTAIRS", "asset/textures/placeholder.png", true},
    {"tex_GRLTGLOW", "asset/textures/placeholder.png", true},
    {"tex_GRNDWALL", "asset/textures/placeholder.png", true},
    {"tex_PITENTB", "asset/textures/placeholder.png", true},
    {"tex_PITTENTA", "asset/textures/placeholder.png", true},
    {"tex_PTENTC", "asset/textures/placeholder.png", true},
    {"tex_PTENTD", "asset/textures/placeholder.png", true},
    {"tex_ROOFTOP", "asset/textures/placeholder.png", true},
    {"tex_TVAN", "asset/textures/placeholder.png", true},
    {"tex_WALGGG", "asset/textures/placeholder.png", true},
    {"tex_AIRCON", "asset/textures/AIRCON.png", true},
    {"tex_AIRCONOLD", "asset/textures/AIRCONOLD.png", true},
    {"tex_BARRELA", "asset/textures/BARRELA.png", true},
    {"tex_BILLBRDA", "asset/textures/BILLBRDA.png", true},
    {"tex_BILLBRDBK", "asset/textures/BILLBRDBK.png", true},
    {"tex_BRDGSDA", "asset/textures/BRDGSDA.png", true},
    {"tex_BRNCHA", "asset/textures/BRNCHA.png", true},
    {"tex_BRNCHB", "asset/textures/BRNCHB.png", true},
    {"tex_BRNCHC", "asset/textures/BRNCHC.png", true},
    {"tex_BULBGLO", "asset/textures/BULBGLO.png", true},
    {"tex_BULBGLO_LONG", "asset/textures/BULBGLO_LONG.png", true},
    {"tex_CEILINGA", "asset/textures/CEILINGA.png", true},
    {"tex_CEMY", "asset/textures/CEMY.png", true},
    {"tex_CEMZ", "asset/textures/CEMZ.png", true},
    {"tex_CMWLLA", "asset/textures/CMWLLA.png", true},
    {"tex_CNUMB", "asset/textures/CNUMB.png", true},
    {"tex_CONE", "asset/textures/CONE.png", true},
    {"tex_CWORKERA", "asset/textures/CWORKERA.png", true},
    {"tex_EBOXA", "asset/textures/EBOXA.png", true},
    {"tex_FENCEA", "asset/textures/FENCEA.png", true},
    {"tex_FENCEATOP", "asset/textures/FENCEATOP.png", true},
    {"tex_FENCEB", "asset/textures/FENCEB.png", true},
    {"tex_FENCEC", "asset/textures/FENCEC.png", true},
    {"tex_FLAGLINEA", "asset/textures/FLAGLINEA.png", true},
    {"tex_FPOSTWDA", "asset/textures/FPOSTWDA.png", true},
    {"tex_FPOSTWDB", "asset/textures/FPOSTWDB.png", true},
    {"tex_GARAGES", "asset/textures/GARAGES.png", true},
    {"tex_GBLADESD", "asset/textures/GBLADESD.png", true},
    {"tex_GBLADESE", "asset/textures/GBLADESE.png", true},
    {"tex_GCAB", "asset/textures/GCAB.png", true},
    {"tex_GDOOR", "asset/textures/GDOOR.png", true},
    {"tex_GRASSA", "asset/textures/GRASSA.png", true},
    {"tex_GRASSAX", "asset/textures/GRASSAX.png", true},
    {"tex_GRASSB", "asset/textures/GRASSB.png", true},
    {"tex_GRASSC", "asset/textures/GRASSC.png", true},
    {"tex_GRASSRUF", "asset/textures/GRASSRUF.png", true},
    {"tex_GRASSYARD", "asset/textures/GRASSYARD.png", true},
    {"tex_GRAVTRANS", "asset/textures/GRAVTRANS.png", true},
    {"tex_GRDRA", "asset/textures/GRDRA.png", true},
    {"tex_GRDRB", "asset/textures/GRDRB.png", true},
    {"tex_GRLT", "asset/textures/GRLT.png", true},
    {"tex_GRNGLOW", "asset/textures/GRNGLOW.png", true},
    {"tex_GRVL", "asset/textures/GRVL.png", true},
    {"tex_GSSIDE", "asset/textures/GSSIDE.png", true},
    {"tex_GURDRA", "asset/textures/GURDRA.png", true},
    {"tex_GURDRB", "asset/textures/GURDRB.png", true},
    {"tex_GURDRC", "asset/textures/GURDRC.png", true},
    {"tex_GURDRCRSSA", "asset/textures/GURDRCRSSA.png", true},
    {"tex_HILLSIDE", "asset/textures/HILLSIDE.png", true},
    {"tex_INBUILDA", "asset/textures/INBUILDA.png", true},
    {"tex_INBUILDB", "asset/textures/INBUILDB.png", true},
    {"tex_LIGHTA", "asset/textures/LIGHTA.png", true},
    {"tex_LOGOA", "asset/textures/LOGOA.png", true},
    {"tex_LOGOB", "asset/textures/LOGOB.png", true},
    {"tex_LOGOC", "asset/textures/LOGOC.png", true},
    {"tex_LOGOD", "asset/textures/LOGOD.png", true},
    {"tex_LOGOE", "asset/textures/LOGOE.png", true},
    {"tex_LOGOSYN", "asset/textures/LOGOSYN.png", true},
    {"tex_OCLOGO", "asset/textures/OCLOGO.png", true},
    {"tex_OUTHOUSE", "asset/textures/OUTHOUSE.png", true},
    {"tex_OVRHDLGHT", "asset/textures/OVRHDLGHT.png", true},
    {"tex_PBOXA", "asset/textures/PBOXA.png", true},
    {"tex_PEOPLEA", "asset/textures/PEOPLEA.png", true},
    {"tex_PEOPLEB", "asset/textures/PEOPLEB.png", true},
    {"tex_PEOPLSDA", "asset/textures/PEOPLSDA.png", true},
    {"tex_PEOPLSDB", "asset/textures/PEOPLSDB.png", true},
    {"tex_PEOPLSDC", "asset/textures/PEOPLSDC.png", true},
    {"tex_PIPES", "asset/textures/PIPES.png", true},
    {"tex_RAILA", "asset/textures/RAILA.png", true},
    {"tex_RDGLOW", "asset/textures/RDGLOW.png", true},
    {"tex_RDLT", "asset/textures/RDLT.png", true},
    {"tex_RGEDGE", "asset/textures/RGEDGE.png", true},
    {"tex_RMBLA", "asset/textures/RMBLA.png", true},
    {"tex_RMBLB", "asset/textures/RMBLB.png", true},
    {"tex_ROADA", "asset/textures/ROADA.png", true},
    {"tex_ROADAB", "asset/textures/ROADAB.png", true},
    {"tex_ROADB", "asset/textures/ROADB.png", true},
    {"tex_ROADGFLOOR", "asset/textures/ROADGFLOOR.png", true},
    {"tex_ROADGRID", "asset/textures/ROADGRID.png", true},
    {"tex_ROADPIT", "asset/textures/ROADPIT.png", true},
    {"tex_ROADSTRP", "asset/textures/ROADSTRP.png", true},
    {"tex_RVA", "asset/textures/RVA.png", true},
    {"tex_SIGN_100", "asset/textures/SIGN_100.png", true},
    {"tex_SIGN_150", "asset/textures/SIGN_150.png", true},
    {"tex_SIGN_50", "asset/textures/SIGN_50.png", true},
    {"tex_STAIRSA", "asset/textures/STAIRSA.png", true},
    {"tex_STARTLINE", "asset/textures/STARTLINE.png", true},
    {"tex_TBOOTH", "asset/textures/TBOOTH.png", true},
    {"tex_TBRANCHA", "asset/textures/TBRANCHA.png", true},
    {"tex_TCAN", "asset/textures/TCAN.png", true},
    {"tex_TENTA", "asset/textures/TENTA.png", true},
    {"tex_TENTB", "asset/textures/TENTB.png", true},
    {"tex_TENTC", "asset/textures/TENTC.png", true},
    {"tex_TENTD", "asset/textures/TENTD.png", true},
    {"tex_TIRESA", "asset/textures/TIRESA.png", true},
    {"tex_TREELRGA", "asset/textures/TREELRGA.png", true},
    {"tex_TREELRGB", "asset/textures/TREELRGB.png", true},
    {"tex_TREELRGC", "asset/textures/TREELRGC.png", true},
    {"tex_TREEWALLA", "asset/textures/TREEWALLA.png", true},
    {"tex_TRETRNKA", "asset/textures/TRETRNKA.png", true},
    {"tex_UNDERA", "asset/textures/UNDERA.png", true},
    {"tex_WALLGA", "asset/textures/WALLGA.png", true},
    {"tex_WALL_BAIG", "asset/textures/WALL_BAIG.png", true},
    {"tex_WALL_BLUEA", "asset/textures/WALL_BLUEA.png", true},
    {"tex_WALL_WHTA", "asset/textures/WALL_WHTA.png", true},
    {"tex_WDFENCE", "asset/textures/WDFENCE.png", true},
    {"tex_WINDA", "asset/textures/WINDA.png", true},
    {"tex_WIREA", "asset/textures/WIREA.png", true},
    {"tex_YLOGLOW", "asset/textures/YLOGLOW.png", true},
    {"tex_YLOLT", "asset/textures/YLOLT.png", true}
};
